services:
  postgres:
    image: 'postgres:15'
    container_name: metalrelease_postgres_parser
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5434:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - parser-service-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  parser-service:
    build:
      context: ..
      dockerfile: MetalReleaseTracker.ParserService/Dockerfile
    container_name: metalrelease_parser_service
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__ParserServiceConnectionString=Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - ConnectionStrings__TickerQConnectionString=Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - Kafka__BootstrapServers=kafka:9092
      - Minio__Endpoint=minio:9001
      - Minio__AccessKey=${MINIO_ROOT_USER}
      - Minio__SecretKey=${MINIO_ROOT_PASSWORD}
      - Minio__BucketName=${MINIO_BUCKET_NAME}
      - Minio__Region=us-east-1
      - OpenTelemetry__OtlpEndpoint=http://otel-collector:4317
      - Serilog__WriteTo__1__Name=OpenTelemetry
      - Serilog__WriteTo__1__Args__Endpoint=http://otel-collector:4318
      - Serilog__WriteTo__1__Args__Protocol=HttpProtobuf
      - TickerQ__Dashboard__Enabled=true
      - TickerQ__Dashboard__BasePath=/tickerq/dashboard
      - TickerQ__Dashboard__Username=${TICKERQ_DASHBOARD_USERNAME}
      - TickerQ__Dashboard__Password=${TICKERQ_DASHBOARD_PASSWORD}
    ports:
      - '5000:8080'
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - parser-service-network
      - metalrelease_shared_net
    restart: unless-stopped

networks:
  parser-service-network:
    driver: bridge
  metalrelease_shared_net:
    external: true

volumes:
  postgres_data: